export const setting = {
    forPage: 'test-template',
    path: 'src/app/ofmodules/test-template/component',
    name: 'popup',
    title: '组件',
    formPrams: 'formPrams',
    formService: [
        {
            name: 'add',
            method: 'doPost',
            url: 'component',
        },
        {
            name: 'edit',
            method: 'doPut',
            url: 'component',
        },
    ],
    inputs: [
        {
            label: '设备名称',
            type: 'text',
            formControlName: 'assetName',
            initValue: '',
            validators: [
                {
                    name: 'Validators.required',
                    tip: '请输入组件名称',
                    errorType: 'required',
                },
                {
                    name: 'this.validate.ports()',
                    tip: '请输入正确的组件格式',
                    errorType: 'error',
                },
            ],
            updateOn: 'blur',
            param: 'assetName',
        },
        {
            label: '设备类型',
            type: 'dropdown',
            mode: 'normal',
            getListFn: 'assettypeList',
            formControlName: 'assetType',
            initValue: '',
            validators: [],
            options: 'assettypes',
            componentTypeList: 'service',
            dataList: {
                label: 'employeeName',
                titleLabel: 'employeeName',
                value: 'id',
            },
            service: {
                name: 'getAssettypeList',
                method: 'doGet',
                url: 'asset/enum/statusmachine/asset_type',
            },
            param: '{page:0,size:0}',
        },
        {
            label: '员工',
            type: 'dropdown',
            mode: 'lazy',
            getListFn: 'staffMenuList',
            formControlName: 'employeeId',
            initValue: '',
            validators: [],
            options: 'staffemnu',
            componentTypeList: 'service',
            params: 'ename',
            selector: 'dropFilterStaff',
            events: {
                onShow: 'changeStaffMenuFilter()',
                onFilterChange: 'filterStaffMenu($event)',
                onChange: 'changeStaffMenuSelected($event)',
            },
            dataList: {
                label: 'employeeName',
                titleLabel: 'employeeName',
                value: 'id',
            },
            service: {
                name: 'getStaffList',
                method: 'doPost',
                url: 'asset/enum/empandempid',
            },
            param: 'empid',
        },
    ],
};
